version: '3.8'

services:
  db:
    image: postgres
    container_name: db-user-container
    restart: on-failure
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_DB: UserDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - ds-management-network
  app:
    hostname: user-management
    restart: on-failure
    depends_on:
      - db
    image: user-manager-service
    container_name: user-management-container
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - DB_IP=db
      - DEVICE_PORT=8000
      - DEVICE_HOST=device-manager
    networks:
      - ds-management-network

networks:
  ds-management-network:
    external: true